# Copyright 2023 StreamNative, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "oxia-cluster.server.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "oxia-cluster.server.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Release.Name }}-svc
  podManagementPolicy: Parallel
  template:
    metadata:
      annotations:
        prometheus.io/port: "{{ include "oxia-cluster.port" .Values.server.config.observability.metric.bindAddress }}"
        prometheus.io/scrape: "{{ .Values.monitoringEnabled }}"
      labels:
        oxia_cluster: {{ .Release.Name }}
        {{- include "oxia-cluster.server.labels" . | nindent 8 }}
      name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        fsGroup: 10001
      containers:
        - command:
            - "oxia"
            - "server"
            - "--sconfig=/oxia/conf/dataserver.yaml"
            {{- if .Values.pprofEnabled }}
            - "--profile"
            {{- end}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          ports:
            - containerPort: {{ include "oxia-cluster.port" .Values.server.config.server.public.bindAddress | int }}
              name: public
            - containerPort: {{ include "oxia-cluster.port" .Values.server.config.server.internal.bindAddress | int }}
              name: internal
            - containerPort: {{ include "oxia-cluster.port" .Values.server.config.observability.metric.bindAddress | int }}
              name: metrics
          resources:
            requests:
              cpu: {{ .Values.server.cpu }}
              memory: {{ .Values.server.memory }}
            limits:
              cpu: {{ .Values.server.cpu }}
              memory: {{ .Values.server.memory }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: server-config
              mountPath: /oxia/conf
              readOnly: true
          livenessProbe:
            {{- include "oxia-cluster.probe" (include "oxia-cluster.port" .Values.server.config.server.internal.bindAddress) | nindent 12 }}
          readinessProbe:
            {{- include "oxia-cluster.readiness-probe" (include "oxia-cluster.port" .Values.server.config.server.internal.bindAddress) | nindent 12 }}
          startupProbe:
            {{- include "oxia-cluster.startup-probe" (include "oxia-cluster.port" .Values.server.config.server.internal.bindAddress) | nindent 12 }}
        - command:
            - "oxia"
            - "coordinator"
            - "--sconfig=/oxia/conf/coordinator/coordinator.yaml"
            {{- if .Values.pprofEnabled }}
            - "--profile"
            {{- end}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: coordinator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          ports:
            - containerPort: {{ include "oxia-cluster.port" .Values.coordinator.config.server.internal.bindAddress | int }}
              name: coord-internal
            - containerPort: {{ include "oxia-cluster.port" .Values.coordinator.config.observability.metric.bindAddress | int }}
              name: coord-metrics
          resources:
            requests:
              cpu: {{ .Values.coordinator.cpu }}
              memory: {{ .Values.coordinator.memory }}
            limits:
              cpu: {{ .Values.coordinator.cpu }}
              memory: {{ .Values.coordinator.memory }}
          volumeMounts:
            - name: coordinator-config
              mountPath: /oxia/conf/coordinator
              readOnly: true
            - name: cluster-config
              mountPath: /oxia/conf/cluster
              readOnly: true
          livenessProbe:
            {{- include "oxia-cluster.probe" (include "oxia-cluster.port" .Values.coordinator.config.server.internal.bindAddress) | nindent 12 }}
          readinessProbe:
            {{- include "oxia-cluster.probe" (include "oxia-cluster.port" .Values.coordinator.config.server.internal.bindAddress) | nindent 12 }}
      volumes:
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-server
        - name: coordinator-config
          configMap:
            name: {{ .Release.Name }}-coordinator
        - name: cluster-config
          configMap:
            name: {{ .Release.Name }}-cluster
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.server.storageClassName }}
        storageClassName: {{ .Values.server.storageClassName }}
        {{- end}}
        resources:
          requests:
            storage: {{ .Values.server.storage }}
